# Generated by Django 5.2.4 on 2025-09-29 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contextindexdbo',
            name='unique_project_file_path',
        ),
        migrations.RemoveConstraint(
            model_name='domaincontextdbo',
            name='unique_project_domain_type',
        ),
        migrations.RenameIndex(
            model_name='aisessiondbo',
            new_name='ucl_ai_sess_project_115169_idx',
            old_name='ucl_ai_sessions_project_ai_type_idx',
        ),
        migrations.RenameIndex(
            model_name='aisessiondbo',
            new_name='ucl_ai_sess_session_fbd5a4_idx',
            old_name='ucl_ai_sessions_session_start_idx',
        ),
        migrations.RenameIndex(
            model_name='aisessiondbo',
            new_name='ucl_ai_sess_session_0d8919_idx',
            old_name='ucl_ai_sessions_session_end_idx',
        ),
        migrations.RenameIndex(
            model_name='aisessiondbo',
            new_name='ucl_ai_sess_ai_inst_ddace4_idx',
            old_name='ucl_ai_sessions_ai_instance_id_idx',
        ),
        migrations.RenameIndex(
            model_name='contextindexdbo',
            new_name='ucl_context_project_38b3ea_idx',
            old_name='ucl_context_indices_project_file_path_idx',
        ),
        migrations.RenameIndex(
            model_name='contextindexdbo',
            new_name='ucl_context_file_ha_855d98_idx',
            old_name='ucl_context_indices_file_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='contextindexdbo',
            new_name='ucl_context_last_mo_63accc_idx',
            old_name='ucl_context_indices_last_modified_idx',
        ),
        migrations.RenameIndex(
            model_name='contextquerydbo',
            new_name='ucl_context_project_7d8f65_idx',
            old_name='ucl_context_queries_project_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='contextquerydbo',
            new_name='ucl_context_ai_sess_edeb86_idx',
            old_name='ucl_context_queries_ai_session_idx',
        ),
        migrations.RenameIndex(
            model_name='contextresponsedbo',
            new_name='ucl_context_project_f0c338_idx',
            old_name='ucl_context_responses_project_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='contextresponsedbo',
            new_name='ucl_context_query_i_8e6cb7_idx',
            old_name='ucl_context_responses_query_idx',
        ),
        migrations.RenameIndex(
            model_name='contextresponsedbo',
            new_name='ucl_context_process_501bd0_idx',
            old_name='ucl_context_responses_processing_time_idx',
        ),
        migrations.RenameIndex(
            model_name='contextsubscriptiondbo',
            new_name='ucl_context_project_6fbf59_idx',
            old_name='ucl_context_subscriptions_project_active_idx',
        ),
        migrations.RenameIndex(
            model_name='contextsubscriptiondbo',
            new_name='ucl_context_ai_sess_0dad48_idx',
            old_name='ucl_context_subscriptions_ai_session_idx',
        ),
        migrations.RenameIndex(
            model_name='domaincontextdbo',
            new_name='ucl_domain__project_b2f029_idx',
            old_name='ucl_domain_contexts_project_domain_idx',
        ),
        migrations.RenameIndex(
            model_name='domaincontextdbo',
            new_name='ucl_domain__domain__49197d_idx',
            old_name='ucl_domain_contexts_domain_type_idx',
        ),
        migrations.RenameIndex(
            model_name='domaincontextdbo',
            new_name='ucl_domain__last_up_fa8932_idx',
            old_name='ucl_domain_contexts_last_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='projectcontextdbo',
            new_name='ucl_project_name_4214e5_idx',
            old_name='ucl_project_contexts_name_idx',
        ),
        migrations.RenameIndex(
            model_name='projectcontextdbo',
            new_name='ucl_project_last_up_f229b2_idx',
            old_name='ucl_project_contexts_last_updated_idx',
        ),
        migrations.AlterField(
            model_name='projectcontextdbo',
            name='repository_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterUniqueTogether(
            name='contextindexdbo',
            unique_together={('project', 'file_path')},
        ),
        migrations.AlterUniqueTogether(
            name='domaincontextdbo',
            unique_together={('project', 'domain_type')},
        ),
        migrations.AddIndex(
            model_name='contextquerydbo',
            index=models.Index(fields=['query_text'], name='ucl_context_query_t_19ed41_idx'),
        ),
    ]
